### ISSUE TITLE
Couldn't resolve module/action [Question] 

### ISSUE THREAD

**Issue by davidungrean** [T-Systems-MMS/ansible-collection-icinga-director#196]
### Question

Hi,

`ERROR! couldn't resolve module/action 't_systems_mms.icinga_director.icinga_host'. This often indicates a misspelling, missing collection, or incorrect module path.`

![Untitled2](https://user-images.githubusercontent.com/33381844/209829582-a2144fda-35e2-48ed-8ce1-29514f3505a1.jpg)

I'm getting the above error when I try to run the role through Orcharhino Run ansible roles option.

If I run the ansible-playbook from the console, everything works correctly. The host is added to Icinga.

![image](https://user-images.githubusercontent.com/33381844/209828607-b72bc96f-e4cb-49fe-8121-608f05838708.png)

![Untitled](https://user-images.githubusercontent.com/33381844/209829208-015ae3d2-3d56-4598-bc8e-4137d32bfbc5.jpg)

I understand the error, and I've installed the **t_systems_mms** module using _ansible-galaxy collection install_ command.

Besides that, I manually copied the folder **t_systems_mms.icinga director** where ansible is searching for modules

![Untitled3](https://user-images.githubusercontent.com/33381844/209830435-148c6466-d3ed-4b30-ab2a-f534c904ec93.jpg)

Any help will be appreciated!

Thanks,
David

**Comment by rndmh3ro** [comment]
Hi @davidungrean,

please upgrade your Ansible-version, 2.9 is out of support.

Then take a look at https://docs.ansible.com/ansible/latest/collections_guide/index.html

The collection is not supposed to be at the plugins-folder but rather in a separate collections-folder.

**Comment by david-ungurean** [comment]
Hi,

The problem was coming from the wrong setting in Ansible config file.



When changing the foreman core, the third-party module library path changes.

In order to be able to run ansible roles from Orcharhino GUI, you have to assure that the foreman-proxy ansible config file points to the correct module install path.


`/etc/foreman-proxy/ansible.cf`

check collections_paths variable. The module must be present there!

You can install the module by specifying the correct path

`ansible-galaxy collection install t_systems_mms.icinga_director -p /usr/share/ansible/collections/`
